// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: curriculum.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addSlotToPlan = `-- name: AddSlotToPlan :one
INSERT INTO curriculum_plan_slots (plan_id, topic_id, sequence_order, duration_value, duration_unit)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, plan_id, topic_id, sequence_order, duration_value, duration_unit
`

type AddSlotToPlanParams struct {
	PlanID        uuid.UUID
	TopicID       uuid.UUID
	SequenceOrder int32
	DurationValue int32
	DurationUnit  string
}

func (q *Queries) AddSlotToPlan(ctx context.Context, arg AddSlotToPlanParams) (CurriculumPlanSlot, error) {
	row := q.db.QueryRowContext(ctx, addSlotToPlan,
		arg.PlanID,
		arg.TopicID,
		arg.SequenceOrder,
		arg.DurationValue,
		arg.DurationUnit,
	)
	var i CurriculumPlanSlot
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.TopicID,
		&i.SequenceOrder,
		&i.DurationValue,
		&i.DurationUnit,
	)
	return i, err
}

const createActivePeriod = `-- name: CreateActivePeriod :one
INSERT INTO active_curriculum_periods (topic_id, start_date, end_date)
VALUES ($1, $2, $3)
RETURNING id, created_at, topic_id, start_date, end_date
`

type CreateActivePeriodParams struct {
	TopicID   uuid.UUID
	StartDate time.Time
	EndDate   time.Time
}

func (q *Queries) CreateActivePeriod(ctx context.Context, arg CreateActivePeriodParams) (ActiveCurriculumPeriod, error) {
	row := q.db.QueryRowContext(ctx, createActivePeriod, arg.TopicID, arg.StartDate, arg.EndDate)
	var i ActiveCurriculumPeriod
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.TopicID,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const createCurriculumPlan = `-- name: CreateCurriculumPlan :one
INSERT INTO curriculum_plans (name)
VALUES ($1)
RETURNING id, created_at, name
`

func (q *Queries) CreateCurriculumPlan(ctx context.Context, name string) (CurriculumPlan, error) {
	row := q.db.QueryRowContext(ctx, createCurriculumPlan, name)
	var i CurriculumPlan
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Name)
	return i, err
}

const createCurriculumTopic = `-- name: CreateCurriculumTopic :one
INSERT INTO curriculum_topics (name, description, color_code)
VALUES ($1, $2, $3)
RETURNING id, created_at, name, description, color_code
`

type CreateCurriculumTopicParams struct {
	Name        string
	Description sql.NullString
	ColorCode   sql.NullString
}

func (q *Queries) CreateCurriculumTopic(ctx context.Context, arg CreateCurriculumTopicParams) (CurriculumTopic, error) {
	row := q.db.QueryRowContext(ctx, createCurriculumTopic, arg.Name, arg.Description, arg.ColorCode)
	var i CurriculumTopic
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Description,
		&i.ColorCode,
	)
	return i, err
}

const getActivePeriods = `-- name: GetActivePeriods :many
SELECT
  p.id, p.created_at, p.topic_id, p.start_date, p.end_date,
  t.name as topic_name,
  t.description as topic_description,
  t.color_code
FROM active_curriculum_periods p
JOIN curriculum_topics t ON p.topic_id = t.id
WHERE p.end_date >= $1 AND p.start_date <= $2
ORDER BY p.start_date
`

type GetActivePeriodsParams struct {
	EndDate   time.Time
	StartDate time.Time
}

type GetActivePeriodsRow struct {
	ID               uuid.UUID
	CreatedAt        time.Time
	TopicID          uuid.UUID
	StartDate        time.Time
	EndDate          time.Time
	TopicName        string
	TopicDescription sql.NullString
	ColorCode        sql.NullString
}

func (q *Queries) GetActivePeriods(ctx context.Context, arg GetActivePeriodsParams) ([]GetActivePeriodsRow, error) {
	rows, err := q.db.QueryContext(ctx, getActivePeriods, arg.EndDate, arg.StartDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActivePeriodsRow
	for rows.Next() {
		var i GetActivePeriodsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.TopicID,
			&i.StartDate,
			&i.EndDate,
			&i.TopicName,
			&i.TopicDescription,
			&i.ColorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSlotsForPlan = `-- name: GetSlotsForPlan :many
SELECT id, plan_id, topic_id, sequence_order, duration_value, duration_unit FROM curriculum_plan_slots
WHERE plan_id = $1
ORDER BY sequence_order
`

func (q *Queries) GetSlotsForPlan(ctx context.Context, planID uuid.UUID) ([]CurriculumPlanSlot, error) {
	rows, err := q.db.QueryContext(ctx, getSlotsForPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CurriculumPlanSlot
	for rows.Next() {
		var i CurriculumPlanSlot
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.TopicID,
			&i.SequenceOrder,
			&i.DurationValue,
			&i.DurationUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurriculumPlans = `-- name: ListCurriculumPlans :many
SELECT id, created_at, name FROM curriculum_plans ORDER BY created_at DESC
`

func (q *Queries) ListCurriculumPlans(ctx context.Context) ([]CurriculumPlan, error) {
	rows, err := q.db.QueryContext(ctx, listCurriculumPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CurriculumPlan
	for rows.Next() {
		var i CurriculumPlan
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurriculumTopics = `-- name: ListCurriculumTopics :many
SELECT id, created_at, name, description, color_code FROM curriculum_topics ORDER BY name
`

func (q *Queries) ListCurriculumTopics(ctx context.Context) ([]CurriculumTopic, error) {
	rows, err := q.db.QueryContext(ctx, listCurriculumTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CurriculumTopic
	for rows.Next() {
		var i CurriculumTopic
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Name,
			&i.Description,
			&i.ColorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
