// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ActiveCurriculumPeriod struct {
	ID        uuid.UUID
	CreatedAt time.Time
	TopicID   uuid.UUID
	StartDate time.Time
	EndDate   time.Time
}

type CurriculumPlan struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Name      string
}

type CurriculumPlanSlot struct {
	ID            uuid.UUID
	PlanID        uuid.UUID
	TopicID       uuid.UUID
	SequenceOrder int32
	DurationValue int32
	DurationUnit  string
}

type CurriculumTopic struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	Name        string
	Description sql.NullString
	ColorCode   sql.NullString
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID           uuid.UUID
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	PasswordHash string
	UserName     string
	PlatformRole string
}
