// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (password_hash, user_name)
VALUES ($1, $2)
RETURNING id, created_at, updated_at, password_hash, user_name, platform_role
`

type CreateUserParams struct {
	PasswordHash string
	UserName     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.PasswordHash, arg.UserName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.UserName,
		&i.PlatformRole,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, password_hash, user_name, platform_role FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.UserName,
		&i.PlatformRole,
	)
	return i, err
}

const getUserByUserName = `-- name: GetUserByUserName :one
SELECT id, created_at, updated_at, password_hash, user_name, platform_role FROM users
WHERE user_name = $1 LIMIT 1
`

func (q *Queries) GetUserByUserName(ctx context.Context, userName string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUserName, userName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.UserName,
		&i.PlatformRole,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, created_at, updated_at, password_hash, user_name, platform_role FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordHash,
			&i.UserName,
			&i.PlatformRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantAdminRole = `-- name: GrantAdminRole :exec
UPDATE users SET platform_role = 'admin', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) GrantAdminRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, grantAdminRole, id)
	return err
}
