services:
  api-server:
    build:
      context: .
      dockerfile: ./cmd/api-server/Dockerfile
    image: training-organiser-api-server:local
    container_name: api-server
    ports:
      - "8080:8080"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
